### ISSUE TITLE
Create a vagrant file to run environment

### ISSUE THREAD

**Issue by gepetobio** [nelas/cifonauta#129]
We should create a vagrant file with all the minimum requirements to run the environment locally. That would help others to run a copy locally without much problems.

**Comment by gepetobio** [comment]
@nelas I've managed to automate the initial installation of the packages on the VM. But once I get in the VM, this is what I get when I try to run the server:

```
./manage.py runserver 0.0.0.0:8000
Traceback (most recent call last):
  File "./manage.py", line 8, in <module>
    from django.core.management import execute_from_command_line
ImportError: No module named django.core.management
```

There are some other configurations you'll have to let me know :P

**Comment by gepetobio** [comment]
Btw, I've added you as a collaborator on my fork... you can check my vagrant branch [here](https://github.com/gepetobio/cifonauta/tree/vagrant). Check the instructions on the readme file.

**Comment by nelas** [comment]
Hey @gepetobio I don't think I'll use the vagrant approach in the near future, so I'll close this issue for now. Thanks!
