### ISSUE TITLE
Duplicate entries on SearchVector annotation

### ISSUE THREAD

**Issue by nelas** [nelas/cifonauta#137]
When annotating a `QuerySet` with a `SearchVector` duplicate entries are appearing. Using only `person__name` also creates a duplicate entry.

```python
media_list = media_list.annotate(
        search=SearchVector(
            'title',
            'caption',
            'person__name',
            'tag__name',
            'sublocation__name',
            'city__name',
            'state__name',
            'country__name'
            )
        ).filter(search=query)
```

Related issues:
- https://stackoverflow.com/questions/46614257/using-django-searchvector-returns-duplicate-objects
- https://stackoverflow.com/questions/47929597/returning-distinct-objects-sorted-by-searchrank-involving-multiple-tables
- https://stackoverflow.com/questions/37562420/why-annotate-generates-duplicate-entries
- https://stackoverflow.com/questions/37167456/duplicates-in-django-queryset-when-using-annotate-filter-annotate

**Comment by nelas** [comment]
Fixed in 079aa11d6d840336d20a6c3d31aa1413137740ed

Solution was to use `StringAgg` for linked models as `SearchVector(StringAgg('person__name', delimiter=' '))`

**Comment by asjad18** [comment]
Savior

**Comment by george-tenev** [comment]
Hi, @nelas 
Would you explain how this fix works.
How does adding StringAgg('person__name', delimiter=' ') 
fixes the issue. 
I had similar issue and your fix worked for me, thanks!
