### ISSUE TITLE
HTML showing up at the wrong place on the page Media

### ISSUE THREAD

**Issue by Felyppe1** [nelas/cifonauta#194]
**Describe the bug**
When you add any html tag inside #div-container > #container in the base.html, it renders outside #div-container (**ON PAGE MEDIA**).

**To Reproduce**
1. Go to base.html file
2. See that it renders block content and block sidebar (if there is one)
3. Open the page Media
4. Inspect it and see that sidebar renders as sibling of #content.

You can add other html tags and see the same happens with them (only on Media).

**Screenshot**
![render](https://github.com/bruvellu/cifonauta/assets/121322408/241b7b45-be7d-42c0-a084-88ad5adb32ae)

**Comment by bruvellu** [comment]
Oi Felyppe, isso não acontece comigo no develop 488ab431b02dcd620c81935c258a441f1337c604. O aside está dentro da section `content` e do div `content-only`:

![image](https://github.com/bruvellu/cifonauta/assets/361179/1cfc2bd0-20e8-4a28-86f8-e070f2025ade)

Faça um merge do develop para seu feature branch (ou rebase). Estou limpando as classes do grid antigo e movendo estilos para páginas individuais após as mudanças no layout responsivo, veja #183. Retirei, por exemplo, a `class="main"` do header e da section que ainda aparecem no seu screen shot. Pode ser que algumas dessas mudanças resolvam…

Agora, uma coisa que me parece relacionada com o problema é por que para mim aparece `content-only` como classe do div. Segundo [essa alteração](https://github.com/bruvellu/cifonauta/blob/develop/meta/templates/base.html#L81) deveria ser `content-and-sidebar` como no seu, não?

**Comment by Felyppe1** [comment]
Achei o problema. Realmente tinha uma div que não estava fechada.

**Comment by Felyppe1** [comment]
@bruvellu Foi corrigido no PR [Feat/adding responsiveness to media page](https://github.com/bruvellu/cifonauta/pull/197)
