### ISSUE TITLE
Fix `NoReverseMatch at /places/` error

### ISSUE THREAD

**Issue by bruvellu** [nelas/cifonauta#313]
URL matching error for `Country` and possibly `State` and `City`:

```
Reverse for 'country_url' with arguments '('\xa0',)' not found. 1 pattern(s) tried: ['country/(?P<slug>[-a-zA-Z0-9_]+)/\\Z']
```

Probably due to places having the same name. Their slug was unique, but not anymore.

If that's the case, the slug needs to change.

**Comment by castilhovirginia** [comment]
I had put the country's standardized acronym as slug, so as not to have duplicate slugs. However, there was one country that had the slug blank (id=205).  I filled in the slug for that record and saw that the bug was no longer occurring. Please see if this is what resolved it.

**Comment by castilhovirginia** [comment]
But it is still necessary to list only the locations with associated media.

**Comment by bruvellu** [comment]
Thanks, it's resolved.

When I'm fixing #315, I'll also re-standardize the slugs since countries have a mix of acronym and slugified name, cities have their ID, and places have a slugified name.
