### ISSUE TITLE
Gerar sitemaps

### ISSUE THREAD

**Issue by bruvellu** [nelas/cifonauta#63]
Usar o framework do django: http://docs.djangoproject.com/en/dev/ref/contrib/sitemaps/

**Comment by nelas** [comment]
At some point, I disabled sitemaps due to some server issues and never enabled them back. Now I've re-enabled them from bca28f1e785c7f7a3ea847b27bd6df35438c4ae9 to ec77307d3a646c74979469e47611b8e2ccb6bda9 to allow for proper page indexing in the upcoming updates of the Cifonauta database.
